/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    orders: Order;
    presets: Preset;
    products: Product;
    media: Media;
    quotes: Quote;
    filaments: Filament;
    search: Search;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    orders: OrdersSelect<false> | OrdersSelect<true>;
    presets: PresetsSelect<false> | PresetsSelect<true>;
    products: ProductsSelect<false> | ProductsSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    quotes: QuotesSelect<false> | QuotesSelect<true>;
    filaments: FilamentsSelect<false> | FilamentsSelect<true>;
    search: SearchSelect<false> | SearchSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: string;
  };
  fallbackLocale: null;
  globals: {
    'printing-options': PrintingOption;
    'pricing-formula': PricingFormula;
    'admin-details': AdminDetail;
  };
  globalsSelect: {
    'printing-options': PrintingOptionsSelect<false> | PrintingOptionsSelect<true>;
    'pricing-formula': PricingFormulaSelect<false> | PricingFormulaSelect<true>;
    'admin-details': AdminDetailsSelect<false> | AdminDetailsSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: string;
  emailVerified?: string | null;
  name: string;
  image?: string | null;
  email: string;
  role?: ('customer' | 'employee' | 'admin' | 'developer') | null;
  address?:
    | {
        line1: string;
        line2?: string | null;
        city: string;
        postalCode: string;
        country: string;
        id?: string | null;
      }[]
    | null;
  orders?: (string | Order)[] | null;
  subscription?: {
    plan?: ('none' | 'plus') | null;
    status?: ('Active' | 'PastDue' | 'Unpaid' | 'Paused') | null;
    stripeSubscriptionId?: string | null;
    currentPeriodStart?: string | null;
    currentPeriodEnd?: string | null;
  };
  stripeCustomerId?: string | null;
  accounts?:
    | {
        provider: string;
        providerAccountId: string;
        type: 'oidc' | 'oauth' | 'email' | 'webauthn';
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
  enableAPIKey?: boolean | null;
  apiKey?: string | null;
  apiKeyIndex?: string | null;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  _verified?: boolean | null;
  _verificationToken?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "orders".
 */
export interface Order {
  id: string;
  /**
   * The name of the order
   */
  name: string;
  /**
   * The user who placed the order
   */
  customer: string | User;
  prints: (
    | {
        product: string | Product;
        quantity: number;
        /**
         * Price fetched from product at order time
         */
        price: number;
        colour: string;
        /**
         * Mark as printed
         */
        completed?: boolean | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'shopProduct';
      }
    | {
        /**
         * Reference to the original quote
         */
        quote: string | Quote;
        /**
         * The 3D model associated with this item
         */
        model: {
          filename: string;
          filetype: 'stl' | '3mf';
          /**
           * The unique download URL to the model
           */
          modelUrl: string;
          /**
           * The unique download URL to the G-code file
           */
          gcodeUrl: string;
        };
        printingOptions: {
          preset?: (string | null) | Preset;
          layerHeight?: number | null;
          infill?: number | null;
          plastic: string;
          colour: string;
        };
        /**
         * Estimated print time as returned by the slicer
         */
        time?: string | null;
        /**
         * Estimated filament usage in grams as returned by the slicer
         */
        filament?: number | null;
        quantity: number;
        /**
         * Price fetched from quote at order time
         */
        price: number;
        /**
         * Mark as printed
         */
        completed?: boolean | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'customPrint';
      }
  )[];
  payment?: {
    /**
     * Payment provider used for this order
     */
    provider?: string | null;
    /**
     * Stripe Customer ID
     */
    stripeCustomerId?: string | null;
    /**
     * Stripe Checkout Session ID
     */
    stripeCheckoutSessionId?: string | null;
    /**
     * Stripe Payment Intent ID
     */
    stripePaymentIntentId?: string | null;
    /**
     * Stripe Charge ID
     */
    stripeChargeId?: string | null;
    /**
     * Currency used for this order
     */
    currency?: string | null;
    /**
     * Amount paid
     */
    amount?: number | null;
    status?:
      | (
          | 'awaiting-payment'
          | 'paid'
          | 'failed'
          | 'refunded'
          | 'partially-refunded'
          | 'cancelled'
          | 'expired'
          | 'checkout-failed'
        )
      | null;
    /**
     * Date and time when the payment was made
     */
    paidAt?: string | null;
    /**
     * Whether the payment was refunded
     */
    refunded?: boolean | null;
    /**
     * Amount refunded
     */
    refundedAmount?: number | null;
    /**
     * Date and time when the payment was refunded
     */
    refundedAt?: string | null;
    /**
     * URL to the payment receipt
     */
    receiptUrl?: string | null;
  };
  /**
   * GoShippo details details for the order
   */
  shipping?: {
    /**
     * Shipment ID
     */
    shipmentId?: string | null;
    /**
     * Shipment transaction ID
     */
    transactionId?: string | null;
    /**
     * Shipping carrier
     */
    carrier?: string | null;
    /**
     * Shipping service
     */
    service?: string | null;
    /**
     * Tracking number
     */
    trackingNumber?: string | null;
    /**
     * Tracking URL
     */
    trackingUrl?: string | null;
    /**
     * Shipping label URL
     */
    labelUrl?: string | null;
    /**
     * Date and time when the label was purchased
     */
    labelPurchasedAt?: string | null;
    /**
     * Parcel ID
     */
    parcelId?: string | null;
  };
  /**
   * Dimensions of the final, packaged order for shipping.
   */
  dimensions?: {
    /**
     * Length of the package in centimeters
     */
    length?: number | null;
    /**
     * Width of the package in centimeters
     */
    width?: number | null;
    /**
     * Height of the package in centimeters
     */
    height?: number | null;
    /**
     * Weight of the package in grams
     */
    weight?: number | null;
  };
  shippingAddress?: {
    fullName?: string | null;
    line1?: string | null;
    line2?: string | null;
    city?: string | null;
    county?: string | null;
    postcode?: string | null;
    country?: string | null;
  };
  /**
   * Pricing details for the order. EVERYTHING IN PENCE, ALWAYS.
   */
  pricing: {
    /**
     * The subtotal of the order in pennies (or smallest equivalent of the currency). Calculated from the prints.
     */
    subtotal?: number | null;
    /**
     * The shipping cost of the order. Always 300p.
     */
    shipping?: number | null;
    /**
     * The tax of the order. Always £0 since we are not VAT registered, yet.
     */
    tax?: number | null;
    /**
     * Total Price of everything in this field (subtotal + shipping + tax).
     */
    total?: number | null;
  };
  /**
   * The print queue this order is assigned to
   */
  queue: number;
  status: {
    statuses?:
      | {
          stage: 'in-queue' | 'printing' | 'packaging' | 'shipped' | 'cancelled';
          timestamp: string;
          id?: string | null;
        }[]
      | null;
    /**
     * Current order status
     */
    currentStatus: 'in-queue' | 'printing' | 'packaging' | 'shipped' | 'cancelled';
  };
  /**
   * Comments on this order
   */
  comments?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Products available for purchase in the shop. DO NOT DELETE PRODUCTS, ARCHIVE INSTEAD.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "products".
 */
export interface Product {
  id: string;
  /**
   * The name of the product.
   */
  name: string;
  /**
   * A detailed description of the product
   */
  description: string;
  pictures: (string | Media)[];
  /**
   * The price of the product in GBP (£) (e.g. 1.5)
   */
  price: number;
  /**
   * The estimated print time for the product (e.g. "2h30m")
   */
  time: string;
  /**
   * The number of times this product has been bought
   */
  orders?: number | null;
  /**
   * If true, the product will not be shown in the shop and cannot be purchased.
   */
  archived?: boolean | null;
  printingOptions: {
    plastic: {
      /**
       * The name of the plastic type
       */
      name: string;
      /**
       * A brief description of the plastic type
       */
      description?: string | null;
      colours?:
        | {
            colour: string;
            id?: string | null;
          }[]
        | null;
      id?: string | null;
      blockName?: string | null;
      blockType: 'plastic';
    }[];
    /**
     * The layer height of the product. This is set by the preset and cannot be changed by the user.
     */
    layerHeight: number;
    /**
     * The infill percentage of the product. This is set by the preset and cannot be changed by the user.
     */
    infill: number;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: string;
  /**
   * Alt text for images / caption for videos
   */
  alt: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * Quotes generated for 3D models, used to create orders
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "quotes".
 */
export interface Quote {
  id: string;
  /**
   * The 3D model associated with this item
   */
  model: {
    filename: string;
    filetype: 'stl' | '3mf';
    /**
     * The unique download URL to the model
     */
    modelUrl?: string | null;
    /**
     * The unique download URL to the G-code file
     */
    gcodeUrl?: string | null;
  };
  printingOptions: {
    preset?: (string | null) | Preset;
    layerHeight?: number | null;
    infill?: number | null;
    /**
     * The plastic/material ID
     */
    plastic: string;
    /**
     * The colour ID
     */
    colour: string;
  };
  /**
   * The user who requested the quote
   */
  customer: string | User;
  /**
   * Estimated filament usage in grams as returned by the slicer
   */
  filament?: number | null;
  /**
   * Estimated print time as returned by the slicer (total)
   */
  time?: string | null;
  price?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "presets".
 */
export interface Preset {
  id: string;
  /**
   * The name of the preset
   */
  name: string;
  /**
   * A brief description of the preset
   */
  description?: string | null;
  /**
   * The filename of the profile of the preset (process) in Bambu Studio/Orca Slicer. DO NOT INCLUDE FILE EXTENSION. See C:\Program Files\OrcaSlicer\resources\profiles\BBL\process
   */
  bambulabName?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "filaments".
 */
export interface Filament {
  id: string;
  /**
   * The name of the filament/material. USE THIS FORMAT: PLA, PETG, ABS, etc.
   */
  name: string;
  /**
   * JSON data from filament folder in Bambu Labs or Orca Slicer. Path: C:/Program Files/OrcaSlicer/resources/profiles/BBL
   */
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This is a collection of automatically created search results. These results are used by the global site search and will be updated automatically as documents in the CMS are created or updated.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "search".
 */
export interface Search {
  id: string;
  title?: string | null;
  priority?: number | null;
  doc: {
    relationTo: 'products';
    value: string | Product;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: string;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: string;
  document?:
    | ({
        relationTo: 'users';
        value: string | User;
      } | null)
    | ({
        relationTo: 'orders';
        value: string | Order;
      } | null)
    | ({
        relationTo: 'presets';
        value: string | Preset;
      } | null)
    | ({
        relationTo: 'products';
        value: string | Product;
      } | null)
    | ({
        relationTo: 'media';
        value: string | Media;
      } | null)
    | ({
        relationTo: 'quotes';
        value: string | Quote;
      } | null)
    | ({
        relationTo: 'filaments';
        value: string | Filament;
      } | null)
    | ({
        relationTo: 'search';
        value: string | Search;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: string;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: string;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  id?: T;
  emailVerified?: T;
  name?: T;
  image?: T;
  email?: T;
  role?: T;
  address?:
    | T
    | {
        line1?: T;
        line2?: T;
        city?: T;
        postalCode?: T;
        country?: T;
        id?: T;
      };
  orders?: T;
  subscription?:
    | T
    | {
        plan?: T;
        status?: T;
        stripeSubscriptionId?: T;
        currentPeriodStart?: T;
        currentPeriodEnd?: T;
      };
  stripeCustomerId?: T;
  accounts?:
    | T
    | {
        provider?: T;
        providerAccountId?: T;
        type?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  enableAPIKey?: T;
  apiKey?: T;
  apiKeyIndex?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  _verified?: T;
  _verificationToken?: T;
  loginAttempts?: T;
  lockUntil?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "orders_select".
 */
export interface OrdersSelect<T extends boolean = true> {
  name?: T;
  customer?: T;
  prints?:
    | T
    | {
        shopProduct?:
          | T
          | {
              product?: T;
              quantity?: T;
              price?: T;
              colour?: T;
              completed?: T;
              id?: T;
              blockName?: T;
            };
        customPrint?:
          | T
          | {
              quote?: T;
              model?:
                | T
                | {
                    filename?: T;
                    filetype?: T;
                    modelUrl?: T;
                    gcodeUrl?: T;
                  };
              printingOptions?:
                | T
                | {
                    preset?: T;
                    layerHeight?: T;
                    infill?: T;
                    plastic?: T;
                    colour?: T;
                  };
              time?: T;
              filament?: T;
              quantity?: T;
              price?: T;
              completed?: T;
              id?: T;
              blockName?: T;
            };
      };
  payment?:
    | T
    | {
        provider?: T;
        stripeCustomerId?: T;
        stripeCheckoutSessionId?: T;
        stripePaymentIntentId?: T;
        stripeChargeId?: T;
        currency?: T;
        amount?: T;
        status?: T;
        paidAt?: T;
        refunded?: T;
        refundedAmount?: T;
        refundedAt?: T;
        receiptUrl?: T;
      };
  shipping?:
    | T
    | {
        shipmentId?: T;
        transactionId?: T;
        carrier?: T;
        service?: T;
        trackingNumber?: T;
        trackingUrl?: T;
        labelUrl?: T;
        labelPurchasedAt?: T;
        parcelId?: T;
      };
  dimensions?:
    | T
    | {
        length?: T;
        width?: T;
        height?: T;
        weight?: T;
      };
  shippingAddress?:
    | T
    | {
        fullName?: T;
        line1?: T;
        line2?: T;
        city?: T;
        county?: T;
        postcode?: T;
        country?: T;
      };
  pricing?:
    | T
    | {
        subtotal?: T;
        shipping?: T;
        tax?: T;
        total?: T;
      };
  queue?: T;
  status?:
    | T
    | {
        statuses?:
          | T
          | {
              stage?: T;
              timestamp?: T;
              id?: T;
            };
        currentStatus?: T;
      };
  comments?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "presets_select".
 */
export interface PresetsSelect<T extends boolean = true> {
  name?: T;
  description?: T;
  bambulabName?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "products_select".
 */
export interface ProductsSelect<T extends boolean = true> {
  name?: T;
  description?: T;
  pictures?: T;
  price?: T;
  time?: T;
  orders?: T;
  archived?: T;
  printingOptions?:
    | T
    | {
        plastic?:
          | T
          | {
              plastic?:
                | T
                | {
                    name?: T;
                    description?: T;
                    colours?:
                      | T
                      | {
                          colour?: T;
                          id?: T;
                        };
                    id?: T;
                    blockName?: T;
                  };
            };
        layerHeight?: T;
        infill?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "quotes_select".
 */
export interface QuotesSelect<T extends boolean = true> {
  model?:
    | T
    | {
        filename?: T;
        filetype?: T;
        modelUrl?: T;
        gcodeUrl?: T;
      };
  printingOptions?:
    | T
    | {
        preset?: T;
        layerHeight?: T;
        infill?: T;
        plastic?: T;
        colour?: T;
      };
  customer?: T;
  filament?: T;
  time?: T;
  price?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "filaments_select".
 */
export interface FilamentsSelect<T extends boolean = true> {
  name?: T;
  data?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "search_select".
 */
export interface SearchSelect<T extends boolean = true> {
  title?: T;
  priority?: T;
  doc?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "printing-options".
 */
export interface PrintingOption {
  id: string;
  plastic?:
    | {
        /**
         * The name of the plastic type
         */
        name: string;
        /**
         * A brief description of the plastic type
         */
        description?: string | null;
        colours?:
          | {
              colour: string;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'plastic';
      }[]
    | null;
  layerHeight: {
    min: number;
    max: number;
  };
  infill: {
    min: number;
    max: number;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Configure the pricing formula for custom prints. Use variables like weight (in grams) and time (in seconds). Example: price = (weight / 1000) + (time * 5)
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pricing-formula".
 */
export interface PricingFormula {
  id: string;
  pricingFormula: string;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "admin-details".
 */
export interface AdminDetail {
  id: string;
  shippingAddress: {
    fullName: string;
    line1: string;
    line2?: string | null;
    city: string;
    county: string;
    postcode: string;
    country: string;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "printing-options_select".
 */
export interface PrintingOptionsSelect<T extends boolean = true> {
  plastic?:
    | T
    | {
        plastic?:
          | T
          | {
              name?: T;
              description?: T;
              colours?:
                | T
                | {
                    colour?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
      };
  layerHeight?:
    | T
    | {
        min?: T;
        max?: T;
      };
  infill?:
    | T
    | {
        min?: T;
        max?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pricing-formula_select".
 */
export interface PricingFormulaSelect<T extends boolean = true> {
  pricingFormula?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "admin-details_select".
 */
export interface AdminDetailsSelect<T extends boolean = true> {
  shippingAddress?:
    | T
    | {
        fullName?: T;
        line1?: T;
        line2?: T;
        city?: T;
        county?: T;
        postcode?: T;
        country?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}